# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62f31ed174a149568ce76465941f8a8124f0b3728446460834e21948f56c8191ae6be427607bda4f5f2b496102af34076af584f4fd6a6b172aeb805d19bd872b

test:
  secret_key_base: 47158c4ae16a4152005c31e9913a52a9221594820999a58a51f1a843c8a19203072f58be33573314f653a5534005bcd3edbbbd612b5a389ad14873f6c190ded9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
